### ISSUE TITLE
GitLab 9.0: GitLab API v4.0

### ISSUE THREAD

**Issue by wahmedswl** [node-gitlab/node-gitlab-legacy#167]
Hi,
   Is GitLab API v4 is supported?

Thanks

**Comment by CiriousJoker** [comment]
Not currently, but I'm looking forward to it

**Comment by EJ-K** [comment]
Hi, any update on this?

**Comment by diegodorgam** [comment]
+1

**Comment by fuchao2012** [comment]
https://github.com/jdalrymple/node-gitlab-api  maybe help.

CoffeeScript is confused for me.
