### ISSUE TITLE
Ucaught error on server unavailability.

### ISSUE THREAD

**Issue by lukjar** [node-gitlab/node-gitlab-legacy#181]
When GitLab server is down API call causes:
```
/usr/src/app/node_modules/gitlab/lib/ApiBaseHTTP.js:88
             return fn(err, ret || JSON.parse(response.body).message);
TypeError: Cannot read property 'body' of null
```
what results in error which is difficult to catch in application code.
Probably the good idea is to check that response is not empty (in fact only err object exists).

**Comment by omerlh** [comment]
Might be related to #136? Anyway, I am experiencing the same issue
