### ISSUE TITLE
Create issues with inexistent tags

### ISSUE THREAD

**Issue by jjimenezlopez** [node-gitlab/node-gitlab-legacy#67]
Hi,

When I try to create an issue with inexistent tags, I get a "true" answer from the issues.create method instead of an error.

**Comment by dave-irvine** [comment]
Do you mean tags (labels) that don't exist yet, or do you mean calling the function without specifying tags?

**Comment by jjimenezlopez** [comment]
Sorry, I should have specified. The first case, when you pass labels that don't exist yet. I know that it is a "bad use", I shouldn't pass labels if they don't exist. But I think that the library should answer with an error, isn't it?

Thanks!

**Comment by dave-irvine** [comment]
OK I will take a look.

This sort of depends what the API returns. If the API provides an error for this situation it will be relatively easy to handle that, however if the API thinks your request is OK, then should we really be deciding that the API has it wrong and we should do extra checks to see if we should error or not?

Once we test what the pure API does with your request, we can go from there :)

**Comment by jjimenezlopez** [comment]
Yes, I understand, the first thing here is to know what the API is doing with those kind of requests.

Let me know if I can help in any way.

**Comment by dave-irvine** [comment]
You could always execute the script with DEBUG=* and paste some anonymised data relevant to the POST for your create. :)

**Comment by jjimenezlopez** [comment]
I've been debugging and seems like the error comes from node-slumber, which I can see is yours as well :)

I have two cases, in both of them I get a 'true' answer.

1. When I try to create a project with a name already taken, the server response is this:

![captura de pantalla 2015-02-02 a las 21 11 33](https://cloud.githubusercontent.com/assets/1641139/6008275/aa922834-ab20-11e4-8a84-3601df0a61dc.png)

2. And when I try to create an issue with labels that don't exist, the server answer with this:
![captura de pantalla 2015-02-02 a las 21 17 48](https://cloud.githubusercontent.com/assets/1641139/6008317/fdb6150c-ab20-11e4-96eb-00ac66ef8fb8.png)


So, should I close this issue and open it in node-slumber?

**Comment by dave-irvine** [comment]
Assuming node-slumber passes back the 400 and 500, we should be handling those rather than returning success.

I'll look into this tomorrow if I have time :) Thanks for your hard work!
